# create namespace
apiVersion: v1
kind: Namespace
metadata:
  name: aws-otel-eks
  labels:
    name: aws-otel-eks

include:
  - local:  cwi-addons/01.cwagent.yaml
  - local:  cwi-addons/02.configMap.yaml
  - local:  cwi-addons/03.daemonset.yaml